FROM golang:1-bookworm AS builder
WORKDIR /app
COPY orchestrator/ orchestrator/
WORKDIR /app/orchestrator
RUN go mod download
RUN CGO_ENABLED=0 go build -o /server ./cmd/server

FROM gcr.io/distroless/static-debian12
COPY --from=builder /server /server
EXPOSE 8080
CMD ["/server"]
