// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: emotion_engine/v1/emotion_engine.proto

package emotion_enginev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EmotionEngineService_TransitionState_FullMethodName      = "/emotion_engine.v1.EmotionEngineService/TransitionState"
	EmotionEngineService_ComputeEmotionVector_FullMethodName = "/emotion_engine.v1.EmotionEngineService/ComputeEmotionVector"
	EmotionEngineService_FuseScores_FullMethodName           = "/emotion_engine.v1.EmotionEngineService/FuseScores"
	EmotionEngineService_EvaluatePromotion_FullMethodName    = "/emotion_engine.v1.EmotionEngineService/EvaluatePromotion"
	EmotionEngineService_ProcessInteraction_FullMethodName   = "/emotion_engine.v1.EmotionEngineService/ProcessInteraction"
)

// EmotionEngineServiceClient is the client API for EmotionEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmotionEngineServiceClient interface {
	TransitionState(ctx context.Context, in *TransitionStateRequest, opts ...grpc.CallOption) (*TransitionStateResponse, error)
	ComputeEmotionVector(ctx context.Context, in *ComputeEmotionVectorRequest, opts ...grpc.CallOption) (*ComputeEmotionVectorResponse, error)
	FuseScores(ctx context.Context, in *FuseScoresRequest, opts ...grpc.CallOption) (*FuseScoresResponse, error)
	EvaluatePromotion(ctx context.Context, in *EvaluatePromotionRequest, opts ...grpc.CallOption) (*EvaluatePromotionResponse, error)
	ProcessInteraction(ctx context.Context, in *ProcessInteractionRequest, opts ...grpc.CallOption) (*ProcessInteractionResponse, error)
}

type emotionEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmotionEngineServiceClient(cc grpc.ClientConnInterface) EmotionEngineServiceClient {
	return &emotionEngineServiceClient{cc}
}

func (c *emotionEngineServiceClient) TransitionState(ctx context.Context, in *TransitionStateRequest, opts ...grpc.CallOption) (*TransitionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TransitionStateResponse)
	err := c.cc.Invoke(ctx, EmotionEngineService_TransitionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionEngineServiceClient) ComputeEmotionVector(ctx context.Context, in *ComputeEmotionVectorRequest, opts ...grpc.CallOption) (*ComputeEmotionVectorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ComputeEmotionVectorResponse)
	err := c.cc.Invoke(ctx, EmotionEngineService_ComputeEmotionVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionEngineServiceClient) FuseScores(ctx context.Context, in *FuseScoresRequest, opts ...grpc.CallOption) (*FuseScoresResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FuseScoresResponse)
	err := c.cc.Invoke(ctx, EmotionEngineService_FuseScores_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionEngineServiceClient) EvaluatePromotion(ctx context.Context, in *EvaluatePromotionRequest, opts ...grpc.CallOption) (*EvaluatePromotionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluatePromotionResponse)
	err := c.cc.Invoke(ctx, EmotionEngineService_EvaluatePromotion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emotionEngineServiceClient) ProcessInteraction(ctx context.Context, in *ProcessInteractionRequest, opts ...grpc.CallOption) (*ProcessInteractionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessInteractionResponse)
	err := c.cc.Invoke(ctx, EmotionEngineService_ProcessInteraction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmotionEngineServiceServer is the server API for EmotionEngineService service.
// All implementations must embed UnimplementedEmotionEngineServiceServer
// for forward compatibility.
type EmotionEngineServiceServer interface {
	TransitionState(context.Context, *TransitionStateRequest) (*TransitionStateResponse, error)
	ComputeEmotionVector(context.Context, *ComputeEmotionVectorRequest) (*ComputeEmotionVectorResponse, error)
	FuseScores(context.Context, *FuseScoresRequest) (*FuseScoresResponse, error)
	EvaluatePromotion(context.Context, *EvaluatePromotionRequest) (*EvaluatePromotionResponse, error)
	ProcessInteraction(context.Context, *ProcessInteractionRequest) (*ProcessInteractionResponse, error)
	mustEmbedUnimplementedEmotionEngineServiceServer()
}

// UnimplementedEmotionEngineServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEmotionEngineServiceServer struct{}

func (UnimplementedEmotionEngineServiceServer) TransitionState(context.Context, *TransitionStateRequest) (*TransitionStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransitionState not implemented")
}
func (UnimplementedEmotionEngineServiceServer) ComputeEmotionVector(context.Context, *ComputeEmotionVectorRequest) (*ComputeEmotionVectorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeEmotionVector not implemented")
}
func (UnimplementedEmotionEngineServiceServer) FuseScores(context.Context, *FuseScoresRequest) (*FuseScoresResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FuseScores not implemented")
}
func (UnimplementedEmotionEngineServiceServer) EvaluatePromotion(context.Context, *EvaluatePromotionRequest) (*EvaluatePromotionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluatePromotion not implemented")
}
func (UnimplementedEmotionEngineServiceServer) ProcessInteraction(context.Context, *ProcessInteractionRequest) (*ProcessInteractionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessInteraction not implemented")
}
func (UnimplementedEmotionEngineServiceServer) mustEmbedUnimplementedEmotionEngineServiceServer() {}
func (UnimplementedEmotionEngineServiceServer) testEmbeddedByValue()                              {}

// UnsafeEmotionEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmotionEngineServiceServer will
// result in compilation errors.
type UnsafeEmotionEngineServiceServer interface {
	mustEmbedUnimplementedEmotionEngineServiceServer()
}

func RegisterEmotionEngineServiceServer(s grpc.ServiceRegistrar, srv EmotionEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedEmotionEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EmotionEngineService_ServiceDesc, srv)
}

func _EmotionEngineService_TransitionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TransitionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionEngineServiceServer).TransitionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionEngineService_TransitionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionEngineServiceServer).TransitionState(ctx, req.(*TransitionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionEngineService_ComputeEmotionVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ComputeEmotionVectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionEngineServiceServer).ComputeEmotionVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionEngineService_ComputeEmotionVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionEngineServiceServer).ComputeEmotionVector(ctx, req.(*ComputeEmotionVectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionEngineService_FuseScores_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FuseScoresRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionEngineServiceServer).FuseScores(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionEngineService_FuseScores_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionEngineServiceServer).FuseScores(ctx, req.(*FuseScoresRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionEngineService_EvaluatePromotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluatePromotionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionEngineServiceServer).EvaluatePromotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionEngineService_EvaluatePromotion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionEngineServiceServer).EvaluatePromotion(ctx, req.(*EvaluatePromotionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmotionEngineService_ProcessInteraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessInteractionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmotionEngineServiceServer).ProcessInteraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EmotionEngineService_ProcessInteraction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmotionEngineServiceServer).ProcessInteraction(ctx, req.(*ProcessInteractionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EmotionEngineService_ServiceDesc is the grpc.ServiceDesc for EmotionEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmotionEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "emotion_engine.v1.EmotionEngineService",
	HandlerType: (*EmotionEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TransitionState",
			Handler:    _EmotionEngineService_TransitionState_Handler,
		},
		{
			MethodName: "ComputeEmotionVector",
			Handler:    _EmotionEngineService_ComputeEmotionVector_Handler,
		},
		{
			MethodName: "FuseScores",
			Handler:    _EmotionEngineService_FuseScores_Handler,
		},
		{
			MethodName: "EvaluatePromotion",
			Handler:    _EmotionEngineService_EvaluatePromotion_Handler,
		},
		{
			MethodName: "ProcessInteraction",
			Handler:    _EmotionEngineService_ProcessInteraction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emotion_engine/v1/emotion_engine.proto",
}
