// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: emotion_engine/v1/emotion_engine.proto

package emotion_enginev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EmotionVector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Components    []float32              `protobuf:"fixed32,1,rep,packed,name=components,proto3" json:"components,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmotionVector) Reset() {
	*x = EmotionVector{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmotionVector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmotionVector) ProtoMessage() {}

func (x *EmotionVector) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmotionVector.ProtoReflect.Descriptor instead.
func (*EmotionVector) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{0}
}

func (x *EmotionVector) GetComponents() []float32 {
	if x != nil {
		return x.Components
	}
	return nil
}

type FsmState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StateName     string                 `protobuf:"bytes,1,opt,name=state_name,json=stateName,proto3" json:"state_name,omitempty"`
	MacroState    string                 `protobuf:"bytes,2,opt,name=macro_state,json=macroState,proto3" json:"macro_state,omitempty"`
	EnteredAtMs   int64                  `protobuf:"varint,3,opt,name=entered_at_ms,json=enteredAtMs,proto3" json:"entered_at_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsmState) Reset() {
	*x = FsmState{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsmState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsmState) ProtoMessage() {}

func (x *FsmState) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsmState.ProtoReflect.Descriptor instead.
func (*FsmState) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{1}
}

func (x *FsmState) GetStateName() string {
	if x != nil {
		return x.StateName
	}
	return ""
}

func (x *FsmState) GetMacroState() string {
	if x != nil {
		return x.MacroState
	}
	return ""
}

func (x *FsmState) GetEnteredAtMs() int64 {
	if x != nil {
		return x.EnteredAtMs
	}
	return 0
}

type SusceptibilityMatrix struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []float32              `protobuf:"fixed32,1,rep,packed,name=values,proto3" json:"values,omitempty"`
	Dimension     uint32                 `protobuf:"varint,2,opt,name=dimension,proto3" json:"dimension,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SusceptibilityMatrix) Reset() {
	*x = SusceptibilityMatrix{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SusceptibilityMatrix) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SusceptibilityMatrix) ProtoMessage() {}

func (x *SusceptibilityMatrix) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SusceptibilityMatrix.ProtoReflect.Descriptor instead.
func (*SusceptibilityMatrix) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{2}
}

func (x *SusceptibilityMatrix) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

func (x *SusceptibilityMatrix) GetDimension() uint32 {
	if x != nil {
		return x.Dimension
	}
	return 0
}

type TransitionStateRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentState   *FsmState              `protobuf:"bytes,1,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	Stimulus       string                 `protobuf:"bytes,2,opt,name=stimulus,proto3" json:"stimulus,omitempty"`
	StimulusVector *EmotionVector         `protobuf:"bytes,3,opt,name=stimulus_vector,json=stimulusVector,proto3" json:"stimulus_vector,omitempty"`
	AgentId        string                 `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TransitionStateRequest) Reset() {
	*x = TransitionStateRequest{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionStateRequest) ProtoMessage() {}

func (x *TransitionStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionStateRequest.ProtoReflect.Descriptor instead.
func (*TransitionStateRequest) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{3}
}

func (x *TransitionStateRequest) GetCurrentState() *FsmState {
	if x != nil {
		return x.CurrentState
	}
	return nil
}

func (x *TransitionStateRequest) GetStimulus() string {
	if x != nil {
		return x.Stimulus
	}
	return ""
}

func (x *TransitionStateRequest) GetStimulusVector() *EmotionVector {
	if x != nil {
		return x.StimulusVector
	}
	return nil
}

func (x *TransitionStateRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type TransitionStateResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NewState           *FsmState              `protobuf:"bytes,1,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	TransitionOccurred bool                   `protobuf:"varint,2,opt,name=transition_occurred,json=transitionOccurred,proto3" json:"transition_occurred,omitempty"`
	BlockedReason      string                 `protobuf:"bytes,3,opt,name=blocked_reason,json=blockedReason,proto3" json:"blocked_reason,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TransitionStateResponse) Reset() {
	*x = TransitionStateResponse{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionStateResponse) ProtoMessage() {}

func (x *TransitionStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionStateResponse.ProtoReflect.Descriptor instead.
func (*TransitionStateResponse) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{4}
}

func (x *TransitionStateResponse) GetNewState() *FsmState {
	if x != nil {
		return x.NewState
	}
	return nil
}

func (x *TransitionStateResponse) GetTransitionOccurred() bool {
	if x != nil {
		return x.TransitionOccurred
	}
	return false
}

func (x *TransitionStateResponse) GetBlockedReason() string {
	if x != nil {
		return x.BlockedReason
	}
	return ""
}

type ComputeEmotionVectorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CurrentEmotion *EmotionVector         `protobuf:"bytes,1,opt,name=current_emotion,json=currentEmotion,proto3" json:"current_emotion,omitempty"`
	Trigger        *EmotionVector         `protobuf:"bytes,2,opt,name=trigger,proto3" json:"trigger,omitempty"`
	WMatrix        *SusceptibilityMatrix  `protobuf:"bytes,3,opt,name=w_matrix,json=wMatrix,proto3" json:"w_matrix,omitempty"`
	Baseline       *EmotionVector         `protobuf:"bytes,4,opt,name=baseline,proto3" json:"baseline,omitempty"`
	DecayLambda    float32                `protobuf:"fixed32,5,opt,name=decay_lambda,json=decayLambda,proto3" json:"decay_lambda,omitempty"`
	DeltaTime      float32                `protobuf:"fixed32,6,opt,name=delta_time,json=deltaTime,proto3" json:"delta_time,omitempty"`
	EnableNoise    bool                   `protobuf:"varint,7,opt,name=enable_noise,json=enableNoise,proto3" json:"enable_noise,omitempty"`
	NoiseSigma     float32                `protobuf:"fixed32,8,opt,name=noise_sigma,json=noiseSigma,proto3" json:"noise_sigma,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ComputeEmotionVectorRequest) Reset() {
	*x = ComputeEmotionVectorRequest{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeEmotionVectorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeEmotionVectorRequest) ProtoMessage() {}

func (x *ComputeEmotionVectorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeEmotionVectorRequest.ProtoReflect.Descriptor instead.
func (*ComputeEmotionVectorRequest) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{5}
}

func (x *ComputeEmotionVectorRequest) GetCurrentEmotion() *EmotionVector {
	if x != nil {
		return x.CurrentEmotion
	}
	return nil
}

func (x *ComputeEmotionVectorRequest) GetTrigger() *EmotionVector {
	if x != nil {
		return x.Trigger
	}
	return nil
}

func (x *ComputeEmotionVectorRequest) GetWMatrix() *SusceptibilityMatrix {
	if x != nil {
		return x.WMatrix
	}
	return nil
}

func (x *ComputeEmotionVectorRequest) GetBaseline() *EmotionVector {
	if x != nil {
		return x.Baseline
	}
	return nil
}

func (x *ComputeEmotionVectorRequest) GetDecayLambda() float32 {
	if x != nil {
		return x.DecayLambda
	}
	return 0
}

func (x *ComputeEmotionVectorRequest) GetDeltaTime() float32 {
	if x != nil {
		return x.DeltaTime
	}
	return 0
}

func (x *ComputeEmotionVectorRequest) GetEnableNoise() bool {
	if x != nil {
		return x.EnableNoise
	}
	return false
}

func (x *ComputeEmotionVectorRequest) GetNoiseSigma() float32 {
	if x != nil {
		return x.NoiseSigma
	}
	return 0
}

type ComputeEmotionVectorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewEmotion    *EmotionVector         `protobuf:"bytes,1,opt,name=new_emotion,json=newEmotion,proto3" json:"new_emotion,omitempty"`
	Intensity     float32                `protobuf:"fixed32,2,opt,name=intensity,proto3" json:"intensity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComputeEmotionVectorResponse) Reset() {
	*x = ComputeEmotionVectorResponse{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeEmotionVectorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeEmotionVectorResponse) ProtoMessage() {}

func (x *ComputeEmotionVectorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComputeEmotionVectorResponse.ProtoReflect.Descriptor instead.
func (*ComputeEmotionVectorResponse) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{6}
}

func (x *ComputeEmotionVectorResponse) GetNewEmotion() *EmotionVector {
	if x != nil {
		return x.NewEmotion
	}
	return nil
}

func (x *ComputeEmotionVectorResponse) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

type ScoreCandidate struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MemoryId          string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	SemanticScore     float32                `protobuf:"fixed32,2,opt,name=semantic_score,json=semanticScore,proto3" json:"semantic_score,omitempty"`
	EmotionalScore    float32                `protobuf:"fixed32,3,opt,name=emotional_score,json=emotionalScore,proto3" json:"emotional_score,omitempty"`
	CognitiveScore    float32                `protobuf:"fixed32,4,opt,name=cognitive_score,json=cognitiveScore,proto3" json:"cognitive_score,omitempty"`
	MemoryLevel       uint32                 `protobuf:"varint,5,opt,name=memory_level,json=memoryLevel,proto3" json:"memory_level,omitempty"`
	IsPseudopermanent bool                   `protobuf:"varint,6,opt,name=is_pseudopermanent,json=isPseudopermanent,proto3" json:"is_pseudopermanent,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScoreCandidate) Reset() {
	*x = ScoreCandidate{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreCandidate) ProtoMessage() {}

func (x *ScoreCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreCandidate.ProtoReflect.Descriptor instead.
func (*ScoreCandidate) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{7}
}

func (x *ScoreCandidate) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *ScoreCandidate) GetSemanticScore() float32 {
	if x != nil {
		return x.SemanticScore
	}
	return 0
}

func (x *ScoreCandidate) GetEmotionalScore() float32 {
	if x != nil {
		return x.EmotionalScore
	}
	return 0
}

func (x *ScoreCandidate) GetCognitiveScore() float32 {
	if x != nil {
		return x.CognitiveScore
	}
	return 0
}

func (x *ScoreCandidate) GetMemoryLevel() uint32 {
	if x != nil {
		return x.MemoryLevel
	}
	return 0
}

func (x *ScoreCandidate) GetIsPseudopermanent() bool {
	if x != nil {
		return x.IsPseudopermanent
	}
	return false
}

type FuseScoresRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Candidates      []*ScoreCandidate      `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Alpha           float32                `protobuf:"fixed32,2,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Beta            float32                `protobuf:"fixed32,3,opt,name=beta,proto3" json:"beta,omitempty"`
	Gamma           float32                `protobuf:"fixed32,4,opt,name=gamma,proto3" json:"gamma,omitempty"`
	PseudopermBoost float32                `protobuf:"fixed32,5,opt,name=pseudoperm_boost,json=pseudopermBoost,proto3" json:"pseudoperm_boost,omitempty"`
	CurrentEmotion  *EmotionVector         `protobuf:"bytes,6,opt,name=current_emotion,json=currentEmotion,proto3" json:"current_emotion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FuseScoresRequest) Reset() {
	*x = FuseScoresRequest{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuseScoresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseScoresRequest) ProtoMessage() {}

func (x *FuseScoresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseScoresRequest.ProtoReflect.Descriptor instead.
func (*FuseScoresRequest) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{8}
}

func (x *FuseScoresRequest) GetCandidates() []*ScoreCandidate {
	if x != nil {
		return x.Candidates
	}
	return nil
}

func (x *FuseScoresRequest) GetAlpha() float32 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *FuseScoresRequest) GetBeta() float32 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *FuseScoresRequest) GetGamma() float32 {
	if x != nil {
		return x.Gamma
	}
	return 0
}

func (x *FuseScoresRequest) GetPseudopermBoost() float32 {
	if x != nil {
		return x.PseudopermBoost
	}
	return 0
}

func (x *FuseScoresRequest) GetCurrentEmotion() *EmotionVector {
	if x != nil {
		return x.CurrentEmotion
	}
	return nil
}

type RankedMemory struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	MemoryId              string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	FinalScore            float32                `protobuf:"fixed32,2,opt,name=final_score,json=finalScore,proto3" json:"final_score,omitempty"`
	SemanticContribution  float32                `protobuf:"fixed32,3,opt,name=semantic_contribution,json=semanticContribution,proto3" json:"semantic_contribution,omitempty"`
	EmotionalContribution float32                `protobuf:"fixed32,4,opt,name=emotional_contribution,json=emotionalContribution,proto3" json:"emotional_contribution,omitempty"`
	CognitiveContribution float32                `protobuf:"fixed32,5,opt,name=cognitive_contribution,json=cognitiveContribution,proto3" json:"cognitive_contribution,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RankedMemory) Reset() {
	*x = RankedMemory{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RankedMemory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RankedMemory) ProtoMessage() {}

func (x *RankedMemory) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RankedMemory.ProtoReflect.Descriptor instead.
func (*RankedMemory) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{9}
}

func (x *RankedMemory) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *RankedMemory) GetFinalScore() float32 {
	if x != nil {
		return x.FinalScore
	}
	return 0
}

func (x *RankedMemory) GetSemanticContribution() float32 {
	if x != nil {
		return x.SemanticContribution
	}
	return 0
}

func (x *RankedMemory) GetEmotionalContribution() float32 {
	if x != nil {
		return x.EmotionalContribution
	}
	return 0
}

func (x *RankedMemory) GetCognitiveContribution() float32 {
	if x != nil {
		return x.CognitiveContribution
	}
	return 0
}

type FuseScoresResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ranked        []*RankedMemory        `protobuf:"bytes,1,rep,name=ranked,proto3" json:"ranked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuseScoresResponse) Reset() {
	*x = FuseScoresResponse{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuseScoresResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuseScoresResponse) ProtoMessage() {}

func (x *FuseScoresResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuseScoresResponse.ProtoReflect.Descriptor instead.
func (*FuseScoresResponse) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{10}
}

func (x *FuseScoresResponse) GetRanked() []*RankedMemory {
	if x != nil {
		return x.Ranked
	}
	return nil
}

type MemoryForPromotion struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	MemoryId          string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	EmotionAtCreation *EmotionVector         `protobuf:"bytes,2,opt,name=emotion_at_creation,json=emotionAtCreation,proto3" json:"emotion_at_creation,omitempty"`
	Intensity         float32                `protobuf:"fixed32,3,opt,name=intensity,proto3" json:"intensity,omitempty"`
	CurrentLevel      uint32                 `protobuf:"varint,4,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"`
	AccessFrequency   uint32                 `protobuf:"varint,5,opt,name=access_frequency,json=accessFrequency,proto3" json:"access_frequency,omitempty"`
	ValenceMagnitude  float32                `protobuf:"fixed32,6,opt,name=valence_magnitude,json=valenceMagnitude,proto3" json:"valence_magnitude,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MemoryForPromotion) Reset() {
	*x = MemoryForPromotion{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryForPromotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryForPromotion) ProtoMessage() {}

func (x *MemoryForPromotion) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryForPromotion.ProtoReflect.Descriptor instead.
func (*MemoryForPromotion) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{11}
}

func (x *MemoryForPromotion) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *MemoryForPromotion) GetEmotionAtCreation() *EmotionVector {
	if x != nil {
		return x.EmotionAtCreation
	}
	return nil
}

func (x *MemoryForPromotion) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

func (x *MemoryForPromotion) GetCurrentLevel() uint32 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

func (x *MemoryForPromotion) GetAccessFrequency() uint32 {
	if x != nil {
		return x.AccessFrequency
	}
	return 0
}

func (x *MemoryForPromotion) GetValenceMagnitude() float32 {
	if x != nil {
		return x.ValenceMagnitude
	}
	return 0
}

type EvaluatePromotionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Memories           []*MemoryForPromotion  `protobuf:"bytes,1,rep,name=memories,proto3" json:"memories,omitempty"`
	IntensityThreshold float32                `protobuf:"fixed32,2,opt,name=intensity_threshold,json=intensityThreshold,proto3" json:"intensity_threshold,omitempty"`
	FrequencyThreshold uint32                 `protobuf:"varint,3,opt,name=frequency_threshold,json=frequencyThreshold,proto3" json:"frequency_threshold,omitempty"`
	ValenceThreshold   float32                `protobuf:"fixed32,4,opt,name=valence_threshold,json=valenceThreshold,proto3" json:"valence_threshold,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EvaluatePromotionRequest) Reset() {
	*x = EvaluatePromotionRequest{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePromotionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePromotionRequest) ProtoMessage() {}

func (x *EvaluatePromotionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePromotionRequest.ProtoReflect.Descriptor instead.
func (*EvaluatePromotionRequest) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{12}
}

func (x *EvaluatePromotionRequest) GetMemories() []*MemoryForPromotion {
	if x != nil {
		return x.Memories
	}
	return nil
}

func (x *EvaluatePromotionRequest) GetIntensityThreshold() float32 {
	if x != nil {
		return x.IntensityThreshold
	}
	return 0
}

func (x *EvaluatePromotionRequest) GetFrequencyThreshold() uint32 {
	if x != nil {
		return x.FrequencyThreshold
	}
	return 0
}

func (x *EvaluatePromotionRequest) GetValenceThreshold() float32 {
	if x != nil {
		return x.ValenceThreshold
	}
	return 0
}

type PromotionDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	ShouldPromote bool                   `protobuf:"varint,2,opt,name=should_promote,json=shouldPromote,proto3" json:"should_promote,omitempty"`
	TargetLevel   uint32                 `protobuf:"varint,3,opt,name=target_level,json=targetLevel,proto3" json:"target_level,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromotionDecision) Reset() {
	*x = PromotionDecision{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromotionDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromotionDecision) ProtoMessage() {}

func (x *PromotionDecision) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromotionDecision.ProtoReflect.Descriptor instead.
func (*PromotionDecision) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{13}
}

func (x *PromotionDecision) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *PromotionDecision) GetShouldPromote() bool {
	if x != nil {
		return x.ShouldPromote
	}
	return false
}

func (x *PromotionDecision) GetTargetLevel() uint32 {
	if x != nil {
		return x.TargetLevel
	}
	return 0
}

func (x *PromotionDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EvaluatePromotionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decisions     []*PromotionDecision   `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluatePromotionResponse) Reset() {
	*x = EvaluatePromotionResponse{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluatePromotionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluatePromotionResponse) ProtoMessage() {}

func (x *EvaluatePromotionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluatePromotionResponse.ProtoReflect.Descriptor instead.
func (*EvaluatePromotionResponse) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{14}
}

func (x *EvaluatePromotionResponse) GetDecisions() []*PromotionDecision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

type ProcessInteractionRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentId             string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	CurrentFsmState     *FsmState              `protobuf:"bytes,2,opt,name=current_fsm_state,json=currentFsmState,proto3" json:"current_fsm_state,omitempty"`
	CurrentEmotion      *EmotionVector         `protobuf:"bytes,3,opt,name=current_emotion,json=currentEmotion,proto3" json:"current_emotion,omitempty"`
	Stimulus            string                 `protobuf:"bytes,4,opt,name=stimulus,proto3" json:"stimulus,omitempty"`
	StimulusVector      *EmotionVector         `protobuf:"bytes,5,opt,name=stimulus_vector,json=stimulusVector,proto3" json:"stimulus_vector,omitempty"`
	WMatrix             *SusceptibilityMatrix  `protobuf:"bytes,6,opt,name=w_matrix,json=wMatrix,proto3" json:"w_matrix,omitempty"`
	Baseline            *EmotionVector         `protobuf:"bytes,7,opt,name=baseline,proto3" json:"baseline,omitempty"`
	DecayLambda         float32                `protobuf:"fixed32,8,opt,name=decay_lambda,json=decayLambda,proto3" json:"decay_lambda,omitempty"`
	DeltaTime           float32                `protobuf:"fixed32,9,opt,name=delta_time,json=deltaTime,proto3" json:"delta_time,omitempty"`
	EnableNoise         bool                   `protobuf:"varint,10,opt,name=enable_noise,json=enableNoise,proto3" json:"enable_noise,omitempty"`
	NoiseSigma          float32                `protobuf:"fixed32,11,opt,name=noise_sigma,json=noiseSigma,proto3" json:"noise_sigma,omitempty"`
	ScoreCandidates     []*ScoreCandidate      `protobuf:"bytes,12,rep,name=score_candidates,json=scoreCandidates,proto3" json:"score_candidates,omitempty"`
	Alpha               float32                `protobuf:"fixed32,13,opt,name=alpha,proto3" json:"alpha,omitempty"`
	Beta                float32                `protobuf:"fixed32,14,opt,name=beta,proto3" json:"beta,omitempty"`
	Gamma               float32                `protobuf:"fixed32,15,opt,name=gamma,proto3" json:"gamma,omitempty"`
	PseudopermBoost     float32                `protobuf:"fixed32,16,opt,name=pseudoperm_boost,json=pseudopermBoost,proto3" json:"pseudoperm_boost,omitempty"`
	PromotionCandidates []*MemoryForPromotion  `protobuf:"bytes,17,rep,name=promotion_candidates,json=promotionCandidates,proto3" json:"promotion_candidates,omitempty"`
	IntensityThreshold  float32                `protobuf:"fixed32,18,opt,name=intensity_threshold,json=intensityThreshold,proto3" json:"intensity_threshold,omitempty"`
	FrequencyThreshold  uint32                 `protobuf:"varint,19,opt,name=frequency_threshold,json=frequencyThreshold,proto3" json:"frequency_threshold,omitempty"`
	ValenceThreshold    float32                `protobuf:"fixed32,20,opt,name=valence_threshold,json=valenceThreshold,proto3" json:"valence_threshold,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessInteractionRequest) Reset() {
	*x = ProcessInteractionRequest{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInteractionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInteractionRequest) ProtoMessage() {}

func (x *ProcessInteractionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInteractionRequest.ProtoReflect.Descriptor instead.
func (*ProcessInteractionRequest) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{15}
}

func (x *ProcessInteractionRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ProcessInteractionRequest) GetCurrentFsmState() *FsmState {
	if x != nil {
		return x.CurrentFsmState
	}
	return nil
}

func (x *ProcessInteractionRequest) GetCurrentEmotion() *EmotionVector {
	if x != nil {
		return x.CurrentEmotion
	}
	return nil
}

func (x *ProcessInteractionRequest) GetStimulus() string {
	if x != nil {
		return x.Stimulus
	}
	return ""
}

func (x *ProcessInteractionRequest) GetStimulusVector() *EmotionVector {
	if x != nil {
		return x.StimulusVector
	}
	return nil
}

func (x *ProcessInteractionRequest) GetWMatrix() *SusceptibilityMatrix {
	if x != nil {
		return x.WMatrix
	}
	return nil
}

func (x *ProcessInteractionRequest) GetBaseline() *EmotionVector {
	if x != nil {
		return x.Baseline
	}
	return nil
}

func (x *ProcessInteractionRequest) GetDecayLambda() float32 {
	if x != nil {
		return x.DecayLambda
	}
	return 0
}

func (x *ProcessInteractionRequest) GetDeltaTime() float32 {
	if x != nil {
		return x.DeltaTime
	}
	return 0
}

func (x *ProcessInteractionRequest) GetEnableNoise() bool {
	if x != nil {
		return x.EnableNoise
	}
	return false
}

func (x *ProcessInteractionRequest) GetNoiseSigma() float32 {
	if x != nil {
		return x.NoiseSigma
	}
	return 0
}

func (x *ProcessInteractionRequest) GetScoreCandidates() []*ScoreCandidate {
	if x != nil {
		return x.ScoreCandidates
	}
	return nil
}

func (x *ProcessInteractionRequest) GetAlpha() float32 {
	if x != nil {
		return x.Alpha
	}
	return 0
}

func (x *ProcessInteractionRequest) GetBeta() float32 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *ProcessInteractionRequest) GetGamma() float32 {
	if x != nil {
		return x.Gamma
	}
	return 0
}

func (x *ProcessInteractionRequest) GetPseudopermBoost() float32 {
	if x != nil {
		return x.PseudopermBoost
	}
	return 0
}

func (x *ProcessInteractionRequest) GetPromotionCandidates() []*MemoryForPromotion {
	if x != nil {
		return x.PromotionCandidates
	}
	return nil
}

func (x *ProcessInteractionRequest) GetIntensityThreshold() float32 {
	if x != nil {
		return x.IntensityThreshold
	}
	return 0
}

func (x *ProcessInteractionRequest) GetFrequencyThreshold() uint32 {
	if x != nil {
		return x.FrequencyThreshold
	}
	return 0
}

func (x *ProcessInteractionRequest) GetValenceThreshold() float32 {
	if x != nil {
		return x.ValenceThreshold
	}
	return 0
}

type ProcessInteractionResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	NewFsmState        *FsmState              `protobuf:"bytes,1,opt,name=new_fsm_state,json=newFsmState,proto3" json:"new_fsm_state,omitempty"`
	TransitionOccurred bool                   `protobuf:"varint,2,opt,name=transition_occurred,json=transitionOccurred,proto3" json:"transition_occurred,omitempty"`
	NewEmotion         *EmotionVector         `protobuf:"bytes,3,opt,name=new_emotion,json=newEmotion,proto3" json:"new_emotion,omitempty"`
	NewIntensity       float32                `protobuf:"fixed32,4,opt,name=new_intensity,json=newIntensity,proto3" json:"new_intensity,omitempty"`
	RankedMemories     []*RankedMemory        `protobuf:"bytes,5,rep,name=ranked_memories,json=rankedMemories,proto3" json:"ranked_memories,omitempty"`
	PromotionDecisions []*PromotionDecision   `protobuf:"bytes,6,rep,name=promotion_decisions,json=promotionDecisions,proto3" json:"promotion_decisions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProcessInteractionResponse) Reset() {
	*x = ProcessInteractionResponse{}
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInteractionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInteractionResponse) ProtoMessage() {}

func (x *ProcessInteractionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emotion_engine_v1_emotion_engine_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInteractionResponse.ProtoReflect.Descriptor instead.
func (*ProcessInteractionResponse) Descriptor() ([]byte, []int) {
	return file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP(), []int{16}
}

func (x *ProcessInteractionResponse) GetNewFsmState() *FsmState {
	if x != nil {
		return x.NewFsmState
	}
	return nil
}

func (x *ProcessInteractionResponse) GetTransitionOccurred() bool {
	if x != nil {
		return x.TransitionOccurred
	}
	return false
}

func (x *ProcessInteractionResponse) GetNewEmotion() *EmotionVector {
	if x != nil {
		return x.NewEmotion
	}
	return nil
}

func (x *ProcessInteractionResponse) GetNewIntensity() float32 {
	if x != nil {
		return x.NewIntensity
	}
	return 0
}

func (x *ProcessInteractionResponse) GetRankedMemories() []*RankedMemory {
	if x != nil {
		return x.RankedMemories
	}
	return nil
}

func (x *ProcessInteractionResponse) GetPromotionDecisions() []*PromotionDecision {
	if x != nil {
		return x.PromotionDecisions
	}
	return nil
}

var File_emotion_engine_v1_emotion_engine_proto protoreflect.FileDescriptor

const file_emotion_engine_v1_emotion_engine_proto_rawDesc = "" +
	"\n" +
	"&emotion_engine/v1/emotion_engine.proto\x12\x11emotion_engine.v1\"6\n" +
	"\rEmotionVector\x12\x1e\n" +
	"\n" +
	"components\x18\x01 \x03(\x02R\n" +
	"componentsJ\x05\bd\x10\xc8\x01\"u\n" +
	"\bFsmState\x12\x1d\n" +
	"\n" +
	"state_name\x18\x01 \x01(\tR\tstateName\x12\x1f\n" +
	"\vmacro_state\x18\x02 \x01(\tR\n" +
	"macroState\x12\"\n" +
	"\rentered_at_ms\x18\x03 \x01(\x03R\venteredAtMsJ\x05\bd\x10\xc8\x01\"S\n" +
	"\x14SusceptibilityMatrix\x12\x16\n" +
	"\x06values\x18\x01 \x03(\x02R\x06values\x12\x1c\n" +
	"\tdimension\x18\x02 \x01(\rR\tdimensionJ\x05\bd\x10\xc8\x01\"\xe3\x01\n" +
	"\x16TransitionStateRequest\x12@\n" +
	"\rcurrent_state\x18\x01 \x01(\v2\x1b.emotion_engine.v1.FsmStateR\fcurrentState\x12\x1a\n" +
	"\bstimulus\x18\x02 \x01(\tR\bstimulus\x12I\n" +
	"\x0fstimulus_vector\x18\x03 \x01(\v2 .emotion_engine.v1.EmotionVectorR\x0estimulusVector\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentIdJ\x05\bd\x10\xc8\x01\"\xb2\x01\n" +
	"\x17TransitionStateResponse\x128\n" +
	"\tnew_state\x18\x01 \x01(\v2\x1b.emotion_engine.v1.FsmStateR\bnewState\x12/\n" +
	"\x13transition_occurred\x18\x02 \x01(\bR\x12transitionOccurred\x12%\n" +
	"\x0eblocked_reason\x18\x03 \x01(\tR\rblockedReasonJ\x05\bd\x10\xc8\x01\"\xb3\x03\n" +
	"\x1bComputeEmotionVectorRequest\x12I\n" +
	"\x0fcurrent_emotion\x18\x01 \x01(\v2 .emotion_engine.v1.EmotionVectorR\x0ecurrentEmotion\x12:\n" +
	"\atrigger\x18\x02 \x01(\v2 .emotion_engine.v1.EmotionVectorR\atrigger\x12B\n" +
	"\bw_matrix\x18\x03 \x01(\v2'.emotion_engine.v1.SusceptibilityMatrixR\awMatrix\x12<\n" +
	"\bbaseline\x18\x04 \x01(\v2 .emotion_engine.v1.EmotionVectorR\bbaseline\x12!\n" +
	"\fdecay_lambda\x18\x05 \x01(\x02R\vdecayLambda\x12\x1d\n" +
	"\n" +
	"delta_time\x18\x06 \x01(\x02R\tdeltaTime\x12!\n" +
	"\fenable_noise\x18\a \x01(\bR\venableNoise\x12\x1f\n" +
	"\vnoise_sigma\x18\b \x01(\x02R\n" +
	"noiseSigmaJ\x05\bd\x10\xc8\x01\"\x86\x01\n" +
	"\x1cComputeEmotionVectorResponse\x12A\n" +
	"\vnew_emotion\x18\x01 \x01(\v2 .emotion_engine.v1.EmotionVectorR\n" +
	"newEmotion\x12\x1c\n" +
	"\tintensity\x18\x02 \x01(\x02R\tintensityJ\x05\bd\x10\xc8\x01\"\xff\x01\n" +
	"\x0eScoreCandidate\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12%\n" +
	"\x0esemantic_score\x18\x02 \x01(\x02R\rsemanticScore\x12'\n" +
	"\x0femotional_score\x18\x03 \x01(\x02R\x0eemotionalScore\x12'\n" +
	"\x0fcognitive_score\x18\x04 \x01(\x02R\x0ecognitiveScore\x12!\n" +
	"\fmemory_level\x18\x05 \x01(\rR\vmemoryLevel\x12-\n" +
	"\x12is_pseudopermanent\x18\x06 \x01(\bR\x11isPseudopermanentJ\x05\bd\x10\xc8\x01\"\x93\x02\n" +
	"\x11FuseScoresRequest\x12A\n" +
	"\n" +
	"candidates\x18\x01 \x03(\v2!.emotion_engine.v1.ScoreCandidateR\n" +
	"candidates\x12\x14\n" +
	"\x05alpha\x18\x02 \x01(\x02R\x05alpha\x12\x12\n" +
	"\x04beta\x18\x03 \x01(\x02R\x04beta\x12\x14\n" +
	"\x05gamma\x18\x04 \x01(\x02R\x05gamma\x12)\n" +
	"\x10pseudoperm_boost\x18\x05 \x01(\x02R\x0fpseudopermBoost\x12I\n" +
	"\x0fcurrent_emotion\x18\x06 \x01(\v2 .emotion_engine.v1.EmotionVectorR\x0ecurrentEmotionJ\x05\bd\x10\xc8\x01\"\xf6\x01\n" +
	"\fRankedMemory\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x1f\n" +
	"\vfinal_score\x18\x02 \x01(\x02R\n" +
	"finalScore\x123\n" +
	"\x15semantic_contribution\x18\x03 \x01(\x02R\x14semanticContribution\x125\n" +
	"\x16emotional_contribution\x18\x04 \x01(\x02R\x15emotionalContribution\x125\n" +
	"\x16cognitive_contribution\x18\x05 \x01(\x02R\x15cognitiveContributionJ\x05\bd\x10\xc8\x01\"T\n" +
	"\x12FuseScoresResponse\x127\n" +
	"\x06ranked\x18\x01 \x03(\v2\x1f.emotion_engine.v1.RankedMemoryR\x06rankedJ\x05\bd\x10\xc8\x01\"\xa5\x02\n" +
	"\x12MemoryForPromotion\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12P\n" +
	"\x13emotion_at_creation\x18\x02 \x01(\v2 .emotion_engine.v1.EmotionVectorR\x11emotionAtCreation\x12\x1c\n" +
	"\tintensity\x18\x03 \x01(\x02R\tintensity\x12#\n" +
	"\rcurrent_level\x18\x04 \x01(\rR\fcurrentLevel\x12)\n" +
	"\x10access_frequency\x18\x05 \x01(\rR\x0faccessFrequency\x12+\n" +
	"\x11valence_magnitude\x18\x06 \x01(\x02R\x10valenceMagnitudeJ\x05\bd\x10\xc8\x01\"\xf3\x01\n" +
	"\x18EvaluatePromotionRequest\x12A\n" +
	"\bmemories\x18\x01 \x03(\v2%.emotion_engine.v1.MemoryForPromotionR\bmemories\x12/\n" +
	"\x13intensity_threshold\x18\x02 \x01(\x02R\x12intensityThreshold\x12/\n" +
	"\x13frequency_threshold\x18\x03 \x01(\rR\x12frequencyThreshold\x12+\n" +
	"\x11valence_threshold\x18\x04 \x01(\x02R\x10valenceThresholdJ\x05\bd\x10\xc8\x01\"\x99\x01\n" +
	"\x11PromotionDecision\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12%\n" +
	"\x0eshould_promote\x18\x02 \x01(\bR\rshouldPromote\x12!\n" +
	"\ftarget_level\x18\x03 \x01(\rR\vtargetLevel\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reasonJ\x05\bd\x10\xc8\x01\"f\n" +
	"\x19EvaluatePromotionResponse\x12B\n" +
	"\tdecisions\x18\x01 \x03(\v2$.emotion_engine.v1.PromotionDecisionR\tdecisionsJ\x05\bd\x10\xc8\x01\"\xe2\a\n" +
	"\x19ProcessInteractionRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12G\n" +
	"\x11current_fsm_state\x18\x02 \x01(\v2\x1b.emotion_engine.v1.FsmStateR\x0fcurrentFsmState\x12I\n" +
	"\x0fcurrent_emotion\x18\x03 \x01(\v2 .emotion_engine.v1.EmotionVectorR\x0ecurrentEmotion\x12\x1a\n" +
	"\bstimulus\x18\x04 \x01(\tR\bstimulus\x12I\n" +
	"\x0fstimulus_vector\x18\x05 \x01(\v2 .emotion_engine.v1.EmotionVectorR\x0estimulusVector\x12B\n" +
	"\bw_matrix\x18\x06 \x01(\v2'.emotion_engine.v1.SusceptibilityMatrixR\awMatrix\x12<\n" +
	"\bbaseline\x18\a \x01(\v2 .emotion_engine.v1.EmotionVectorR\bbaseline\x12!\n" +
	"\fdecay_lambda\x18\b \x01(\x02R\vdecayLambda\x12\x1d\n" +
	"\n" +
	"delta_time\x18\t \x01(\x02R\tdeltaTime\x12!\n" +
	"\fenable_noise\x18\n" +
	" \x01(\bR\venableNoise\x12\x1f\n" +
	"\vnoise_sigma\x18\v \x01(\x02R\n" +
	"noiseSigma\x12L\n" +
	"\x10score_candidates\x18\f \x03(\v2!.emotion_engine.v1.ScoreCandidateR\x0fscoreCandidates\x12\x14\n" +
	"\x05alpha\x18\r \x01(\x02R\x05alpha\x12\x12\n" +
	"\x04beta\x18\x0e \x01(\x02R\x04beta\x12\x14\n" +
	"\x05gamma\x18\x0f \x01(\x02R\x05gamma\x12)\n" +
	"\x10pseudoperm_boost\x18\x10 \x01(\x02R\x0fpseudopermBoost\x12X\n" +
	"\x14promotion_candidates\x18\x11 \x03(\v2%.emotion_engine.v1.MemoryForPromotionR\x13promotionCandidates\x12/\n" +
	"\x13intensity_threshold\x18\x12 \x01(\x02R\x12intensityThreshold\x12/\n" +
	"\x13frequency_threshold\x18\x13 \x01(\rR\x12frequencyThreshold\x12+\n" +
	"\x11valence_threshold\x18\x14 \x01(\x02R\x10valenceThresholdJ\x05\bd\x10\xc8\x01\"\x9e\x03\n" +
	"\x1aProcessInteractionResponse\x12?\n" +
	"\rnew_fsm_state\x18\x01 \x01(\v2\x1b.emotion_engine.v1.FsmStateR\vnewFsmState\x12/\n" +
	"\x13transition_occurred\x18\x02 \x01(\bR\x12transitionOccurred\x12A\n" +
	"\vnew_emotion\x18\x03 \x01(\v2 .emotion_engine.v1.EmotionVectorR\n" +
	"newEmotion\x12#\n" +
	"\rnew_intensity\x18\x04 \x01(\x02R\fnewIntensity\x12H\n" +
	"\x0franked_memories\x18\x05 \x03(\v2\x1f.emotion_engine.v1.RankedMemoryR\x0erankedMemories\x12U\n" +
	"\x13promotion_decisions\x18\x06 \x03(\v2$.emotion_engine.v1.PromotionDecisionR\x12promotionDecisionsJ\x05\bd\x10\xc8\x012\xb7\x04\n" +
	"\x14EmotionEngineService\x12h\n" +
	"\x0fTransitionState\x12).emotion_engine.v1.TransitionStateRequest\x1a*.emotion_engine.v1.TransitionStateResponse\x12w\n" +
	"\x14ComputeEmotionVector\x12..emotion_engine.v1.ComputeEmotionVectorRequest\x1a/.emotion_engine.v1.ComputeEmotionVectorResponse\x12Y\n" +
	"\n" +
	"FuseScores\x12$.emotion_engine.v1.FuseScoresRequest\x1a%.emotion_engine.v1.FuseScoresResponse\x12n\n" +
	"\x11EvaluatePromotion\x12+.emotion_engine.v1.EvaluatePromotionRequest\x1a,.emotion_engine.v1.EvaluatePromotionResponse\x12q\n" +
	"\x12ProcessInteraction\x12,.emotion_engine.v1.ProcessInteractionRequest\x1a-.emotion_engine.v1.ProcessInteractionResponseBUZSgithub.com/swarm-emotions/orchestrator/pkg/proto/emotion_engine/v1;emotion_enginev1b\x06proto3"

var (
	file_emotion_engine_v1_emotion_engine_proto_rawDescOnce sync.Once
	file_emotion_engine_v1_emotion_engine_proto_rawDescData []byte
)

func file_emotion_engine_v1_emotion_engine_proto_rawDescGZIP() []byte {
	file_emotion_engine_v1_emotion_engine_proto_rawDescOnce.Do(func() {
		file_emotion_engine_v1_emotion_engine_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emotion_engine_v1_emotion_engine_proto_rawDesc), len(file_emotion_engine_v1_emotion_engine_proto_rawDesc)))
	})
	return file_emotion_engine_v1_emotion_engine_proto_rawDescData
}

var file_emotion_engine_v1_emotion_engine_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_emotion_engine_v1_emotion_engine_proto_goTypes = []any{
	(*EmotionVector)(nil),                // 0: emotion_engine.v1.EmotionVector
	(*FsmState)(nil),                     // 1: emotion_engine.v1.FsmState
	(*SusceptibilityMatrix)(nil),         // 2: emotion_engine.v1.SusceptibilityMatrix
	(*TransitionStateRequest)(nil),       // 3: emotion_engine.v1.TransitionStateRequest
	(*TransitionStateResponse)(nil),      // 4: emotion_engine.v1.TransitionStateResponse
	(*ComputeEmotionVectorRequest)(nil),  // 5: emotion_engine.v1.ComputeEmotionVectorRequest
	(*ComputeEmotionVectorResponse)(nil), // 6: emotion_engine.v1.ComputeEmotionVectorResponse
	(*ScoreCandidate)(nil),               // 7: emotion_engine.v1.ScoreCandidate
	(*FuseScoresRequest)(nil),            // 8: emotion_engine.v1.FuseScoresRequest
	(*RankedMemory)(nil),                 // 9: emotion_engine.v1.RankedMemory
	(*FuseScoresResponse)(nil),           // 10: emotion_engine.v1.FuseScoresResponse
	(*MemoryForPromotion)(nil),           // 11: emotion_engine.v1.MemoryForPromotion
	(*EvaluatePromotionRequest)(nil),     // 12: emotion_engine.v1.EvaluatePromotionRequest
	(*PromotionDecision)(nil),            // 13: emotion_engine.v1.PromotionDecision
	(*EvaluatePromotionResponse)(nil),    // 14: emotion_engine.v1.EvaluatePromotionResponse
	(*ProcessInteractionRequest)(nil),    // 15: emotion_engine.v1.ProcessInteractionRequest
	(*ProcessInteractionResponse)(nil),   // 16: emotion_engine.v1.ProcessInteractionResponse
}
var file_emotion_engine_v1_emotion_engine_proto_depIdxs = []int32{
	1,  // 0: emotion_engine.v1.TransitionStateRequest.current_state:type_name -> emotion_engine.v1.FsmState
	0,  // 1: emotion_engine.v1.TransitionStateRequest.stimulus_vector:type_name -> emotion_engine.v1.EmotionVector
	1,  // 2: emotion_engine.v1.TransitionStateResponse.new_state:type_name -> emotion_engine.v1.FsmState
	0,  // 3: emotion_engine.v1.ComputeEmotionVectorRequest.current_emotion:type_name -> emotion_engine.v1.EmotionVector
	0,  // 4: emotion_engine.v1.ComputeEmotionVectorRequest.trigger:type_name -> emotion_engine.v1.EmotionVector
	2,  // 5: emotion_engine.v1.ComputeEmotionVectorRequest.w_matrix:type_name -> emotion_engine.v1.SusceptibilityMatrix
	0,  // 6: emotion_engine.v1.ComputeEmotionVectorRequest.baseline:type_name -> emotion_engine.v1.EmotionVector
	0,  // 7: emotion_engine.v1.ComputeEmotionVectorResponse.new_emotion:type_name -> emotion_engine.v1.EmotionVector
	7,  // 8: emotion_engine.v1.FuseScoresRequest.candidates:type_name -> emotion_engine.v1.ScoreCandidate
	0,  // 9: emotion_engine.v1.FuseScoresRequest.current_emotion:type_name -> emotion_engine.v1.EmotionVector
	9,  // 10: emotion_engine.v1.FuseScoresResponse.ranked:type_name -> emotion_engine.v1.RankedMemory
	0,  // 11: emotion_engine.v1.MemoryForPromotion.emotion_at_creation:type_name -> emotion_engine.v1.EmotionVector
	11, // 12: emotion_engine.v1.EvaluatePromotionRequest.memories:type_name -> emotion_engine.v1.MemoryForPromotion
	13, // 13: emotion_engine.v1.EvaluatePromotionResponse.decisions:type_name -> emotion_engine.v1.PromotionDecision
	1,  // 14: emotion_engine.v1.ProcessInteractionRequest.current_fsm_state:type_name -> emotion_engine.v1.FsmState
	0,  // 15: emotion_engine.v1.ProcessInteractionRequest.current_emotion:type_name -> emotion_engine.v1.EmotionVector
	0,  // 16: emotion_engine.v1.ProcessInteractionRequest.stimulus_vector:type_name -> emotion_engine.v1.EmotionVector
	2,  // 17: emotion_engine.v1.ProcessInteractionRequest.w_matrix:type_name -> emotion_engine.v1.SusceptibilityMatrix
	0,  // 18: emotion_engine.v1.ProcessInteractionRequest.baseline:type_name -> emotion_engine.v1.EmotionVector
	7,  // 19: emotion_engine.v1.ProcessInteractionRequest.score_candidates:type_name -> emotion_engine.v1.ScoreCandidate
	11, // 20: emotion_engine.v1.ProcessInteractionRequest.promotion_candidates:type_name -> emotion_engine.v1.MemoryForPromotion
	1,  // 21: emotion_engine.v1.ProcessInteractionResponse.new_fsm_state:type_name -> emotion_engine.v1.FsmState
	0,  // 22: emotion_engine.v1.ProcessInteractionResponse.new_emotion:type_name -> emotion_engine.v1.EmotionVector
	9,  // 23: emotion_engine.v1.ProcessInteractionResponse.ranked_memories:type_name -> emotion_engine.v1.RankedMemory
	13, // 24: emotion_engine.v1.ProcessInteractionResponse.promotion_decisions:type_name -> emotion_engine.v1.PromotionDecision
	3,  // 25: emotion_engine.v1.EmotionEngineService.TransitionState:input_type -> emotion_engine.v1.TransitionStateRequest
	5,  // 26: emotion_engine.v1.EmotionEngineService.ComputeEmotionVector:input_type -> emotion_engine.v1.ComputeEmotionVectorRequest
	8,  // 27: emotion_engine.v1.EmotionEngineService.FuseScores:input_type -> emotion_engine.v1.FuseScoresRequest
	12, // 28: emotion_engine.v1.EmotionEngineService.EvaluatePromotion:input_type -> emotion_engine.v1.EvaluatePromotionRequest
	15, // 29: emotion_engine.v1.EmotionEngineService.ProcessInteraction:input_type -> emotion_engine.v1.ProcessInteractionRequest
	4,  // 30: emotion_engine.v1.EmotionEngineService.TransitionState:output_type -> emotion_engine.v1.TransitionStateResponse
	6,  // 31: emotion_engine.v1.EmotionEngineService.ComputeEmotionVector:output_type -> emotion_engine.v1.ComputeEmotionVectorResponse
	10, // 32: emotion_engine.v1.EmotionEngineService.FuseScores:output_type -> emotion_engine.v1.FuseScoresResponse
	14, // 33: emotion_engine.v1.EmotionEngineService.EvaluatePromotion:output_type -> emotion_engine.v1.EvaluatePromotionResponse
	16, // 34: emotion_engine.v1.EmotionEngineService.ProcessInteraction:output_type -> emotion_engine.v1.ProcessInteractionResponse
	30, // [30:35] is the sub-list for method output_type
	25, // [25:30] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_emotion_engine_v1_emotion_engine_proto_init() }
func file_emotion_engine_v1_emotion_engine_proto_init() {
	if File_emotion_engine_v1_emotion_engine_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emotion_engine_v1_emotion_engine_proto_rawDesc), len(file_emotion_engine_v1_emotion_engine_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_emotion_engine_v1_emotion_engine_proto_goTypes,
		DependencyIndexes: file_emotion_engine_v1_emotion_engine_proto_depIdxs,
		MessageInfos:      file_emotion_engine_v1_emotion_engine_proto_msgTypes,
	}.Build()
	File_emotion_engine_v1_emotion_engine_proto = out.File
	file_emotion_engine_v1_emotion_engine_proto_goTypes = nil
	file_emotion_engine_v1_emotion_engine_proto_depIdxs = nil
}
